import type { Metadata } from "next";
import localFont from "next/font/local";
import "./global.css";
import { LayoutStyle } from "./style.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "./_asset/font/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable}`}>
      <body>
        <main className={LayoutStyle}>{children}</main>
      </body>
    </html>
  );
}
